version: '2'
services:
    aipg-app:
        image: aipg
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://aipg-postgresql:5432/aipg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aipg-postgresql:
        extends:
            file: postgresql.yml
            service: aipg-postgresql
